"""Initial migration.

Revision ID: 848094aced04
Revises: 
Create Date: 2024-07-11 14:30:45.142515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848094aced04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_secret', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('otp_secret')

    # ### end Alembic commands ###
